### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by IceIceRabbit** [jflanigan/jamr#16]
while trying to train I came across this error,

> panic: swash_fetch got swatch of unexpected bit width, slen=1024, needents=64 at /home/tempuser/AMRParsing/jamr/tools/cdec/corpus/support/quote-norm.pl line 149, <STDIN> line 1.

**Comment by pedrobalage** [comment]
The same happened to me. I removed the problematic line (149) and now it is working.

OS: Ubuntu 16.04
Perl: v5.22.1

**Comment by IceIceRabbit** [comment]
Ahh yeah it worked, thanks
