### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by cainesap** [jflanigan/jamr#23]
Hello,
When running ./setup to install, I encounter the following error from the ./compile command:
scala.reflect.internal.MissingRequirementError: object scala.runtime in compiler mirror not found.
Is this a bug, something I can work around, or very strange indeed (possibly a problem my end)?
thanks, Andrew

**Comment by Fije** [comment]
@cainesap Probably not relevant to you anymore, but I resolved this issue by installing Java 8 and explicitly directing to this Java version by:
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home

(jdk1.8.0_192.jdk should be your Java  8 version)

**Comment by cainesap** [comment]
Awesome, thank you @Fije, this worked :)

**Comment by espinasseb** [comment]
Helleo,
I would like use JAMR parser on Mac os X.
* Is-it possible ?
* What modifications are necessary ?
Best regards,
Bernard.
